/**
 * Report Generator Controller
 * Manages report creation, exporting (HTML, CSV), retrieving, and file downloading
 */

const fs = require("fs");
const path = require("path");
const Dataset = require("../models/Dataset");
const Report = require("../models/Report");
const { parseCSV, parseExcel } = require("../utils/dataParser");
const { generateExecutiveBriefing } = require("../utils/reportEngine");
const { exportToCSV } = require("../utils/reportExporter");

const readDatasetRows = (filePath, fileType) => {
  const ext = (fileType || path.extname(filePath))
    .toLowerCase()
    .replace(".", "");

  if (["xls", "xlsx"].includes(ext)) {
    return parseExcel(filePath);
  }

  return parseCSV(filePath);
};

/**
 * @desc    Generate and save an Executive Report
 * @route   POST /api/v1/reports/generate
 * @access  Private
 */
const generateReport = async (req, res, next) => {
  try {
    const {
      datasetId,
      title,
      cleaningHistory = [],
      analyticsMeta = {},
      datasetMeta = {},
      statisticalDistributions = {},
    } = req.body;

    if (!datasetId) {
      return res
        .status(400)
        .json({ success: false, error: "Please provide datasetId" });
    }

    const dataset = await Dataset.findOne({
      _id: datasetId,
      user: req.user._id,
    });

    if (!dataset) {
      return res
        .status(404)
        .json({ success: false, error: "Dataset not found" });
    }

    if (!fs.existsSync(dataset.filePath)) {
      return res
        .status(400)
        .json({ success: false, error: "Dataset source file missing" });
    }

    const rows = readDatasetRows(dataset.filePath, dataset.fileType);

    const briefingContent = generateExecutiveBriefing({
      datasetName: dataset.originalName,
      records: rows,
      cleaningHistory,
      analyticsMeta,
      datasetMeta: {
        originalName: dataset.originalName,
        fileType: dataset.fileType,
        rowCount: dataset.rowCount,
        columnCount: dataset.columnCount,
        ...datasetMeta,
      },
      statisticalDistributions,
    });

    const reportTitle = title || `Executive Report - ${dataset.originalName}`;

    const report = await Report.create({
      user: req.user._id,
      dataset: dataset._id,
      title: reportTitle,
      summaryText: briefingContent,
      cleaningHistory,
      analyticsMeta,
      datasetMeta: {
        originalName: dataset.originalName,
        fileType: dataset.fileType,
        rowCount: dataset.rowCount,
        columnCount: dataset.columnCount,
        ...datasetMeta,
      },
      statisticalDistributions,
      metrics: {
        totalRecords: rows.length,
        totalAttributes: rows.length > 0 ? Object.keys(rows[0]).length : 0,
        healthScore: null,
      },
      fileType: "text",
    });

    res.status(201).json({
      success: true,
      message: "Executive Briefing generated successfully",
      data: report,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * @desc    Get all reports generated by logged-in user
 * @route   GET /api/v1/reports
 * @access  Private
 */
const getUserReports = async (req, res, next) => {
  try {
    const reports = await Report.find({ user: req.user._id })
      .populate("dataset", "originalName rowCount columnCount")
      .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      count: reports.length,
      data: reports,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * @desc    Export Dataset as CSV
 * @route   GET /api/v1/reports/export/csv/:datasetId
 * @access  Private
 */
const exportDatasetCSV = async (req, res, next) => {
  try {
    const dataset = await Dataset.findOne({
      _id: req.params.datasetId,
      user: req.user._id,
    });

    if (!dataset) {
      return res
        .status(404)
        .json({ success: false, error: "Dataset not found" });
    }

    if (!fs.existsSync(dataset.filePath)) {
      return res
        .status(400)
        .json({ success: false, error: "Source file missing" });
    }

    const rows = readDatasetRows(dataset.filePath, dataset.fileType);
    const csvContent = exportToCSV(rows);

    const downloadName = `export_${dataset.originalName.replace(/\.[^/.]+$/, "")}.csv`;

    res.setHeader("Content-Type", "text/csv");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${downloadName}"`,
    );
    res.status(200).send(csvContent);
  } catch (error) {
    next(error);
  }
};

/**
 * @desc    Download an existing report
 * @route   GET /api/v1/reports/download/:id
 * @access  Private
 */
const downloadReport = async (req, res, next) => {
  try {
    const report = await Report.findOne({
      _id: req.params.id,
      user: req.user._id,
    });

    if (!report) {
      return res
        .status(404)
        .json({ success: false, error: "Report not found" });
    }

    const fileName = `${report.title.replace(/[^a-zA-Z0-9]/g, "_")}.txt`;

    res.setHeader("Content-Type", "text/plain");
    res.setHeader("Content-Disposition", `attachment; filename="${fileName}"`);
    res.status(200).send(report.summary || "");
  } catch (error) {
    next(error);
  }
};

/**
 * @desc    Delete a report
 * @route   DELETE /api/v1/reports/:id
 * @access  Private
 */
const deleteReport = async (req, res, next) => {
  try {
    const report = await Report.findOne({
      _id: req.params.id,
      user: req.user._id,
    });

    if (!report) {
      return res
        .status(404)
        .json({ success: false, error: "Report not found" });
    }

    await report.deleteOne();

    res.status(200).json({
      success: true,
      message: "Report deleted successfully",
    });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  generateReport,
  getUserReports,
  exportDatasetCSV,
  downloadReport,
  deleteReport,
};
